---
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Code Analysis
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    environment: build
    # OS List
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v5.0.0
      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Use Node.js 22.x
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 22.x
          #cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run unit
      # https://github.com/marketplace/actions/codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      # https://github.com/marketplace/actions/official-fossa-action
      - name: Upload to FOSSA
        uses: fossas/fossa-action@v1.7.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
