---
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    environment: build
    strategy:
      matrix:
        # Windows is currently borked
        # https://github.com/nodejs/node/issues/52682
        # Disabling for now
        # windows-latest
        os: [ubuntu-latest]
        node_version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # OS List
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
    runs-on: ${{ matrix.os }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v5.0.0
      # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v5.0.0
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run build --if-present
      - run: npm test
