import crypto from 'node:crypto';
import fs from 'fs-extra';

const MIN_PASSWORD_ENTROPY_BITS = 60;
const MIN_SECRET_ENTROPY_BITS = 64;
const MIN_SECRET_LENGTH = 32;

function passwordEntropy(password) {
  let poolSize = 0;
  if (/[a-z]/.test(password)) {
    poolSize += 26;
  }
  if (/[A-Z]/.test(password)) {
    poolSize += 26;
  }
  if (/\d/.test(password)) {
    poolSize += 10;
  }
  if (/[^a-zA-Z0-9]/.test(password)) {
    poolSize += 32;
  }
  return poolSize > 0 ? password.length * Math.log2(poolSize) : 0;
}

const ALPHANUMERIC =
  'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

function randomAlphanumeric(length) {
  return Array.from(crypto.randomBytes(length))
    .map((b) => ALPHANUMERIC[b % ALPHANUMERIC.length])
    .join('');
}

function generateCredentials() {
  const username = `raneto_${randomAlphanumeric(8)}`;
  const password = randomAlphanumeric(20);
  return { username, password };
}

function validateConfig(config) {
  const errors = [];
  const warnings = [];

  function require(field, message) {
    if (!field) {
      errors.push(message);
    }
  }

  // Deprecated fields
  if (config.secret !== undefined) {
    warnings.push(
      'config.secret is deprecated; rename it to config.session_secret',
    );
    if (config.session_secret === undefined) {
      config.session_secret = config.secret;
    }
  }

  // Removed fields
  if (config.analytics !== undefined) {
    errors.push(
      'config.analytics has been removed; use config.google_analytics_id with a GA4 measurement ID (e.g. "G-XXXXXXXXXX") instead',
    );
  }

  // Session secret
  if (!config.session_secret || config.session_secret === '') {
    errors.push(
      'config.session_secret is required (set SESSION_SECRET env var or config.session_secret)',
    );
  } else if (config.session_secret.length < MIN_SECRET_LENGTH) {
    errors.push(
      `config.session_secret must be at least ${MIN_SECRET_LENGTH} characters`,
    );
  } else {
    const secretEntropy = passwordEntropy(config.session_secret);
    if (secretEntropy < MIN_SECRET_ENTROPY_BITS) {
      errors.push(
        `config.session_secret is too weak (${Math.floor(secretEntropy)} bits entropy, minimum ${MIN_SECRET_ENTROPY_BITS}); use a random string generated by e.g. openssl rand -base64 32`,
      );
    }
  }

  // Content directory
  require(config.content_dir, 'config.content_dir is required');
  if (config.content_dir && !fs.pathExistsSync(config.content_dir)) {
    errors.push(
      `config.content_dir "${config.content_dir}" does not exist or is not accessible`,
    );
  }

  // Image URL (used for static serving and filtering)
  require(config.image_url, 'config.image_url is required');

  // Base URL must be a string (can be empty)
  if (config.base_url === undefined || config.base_url === null) {
    errors.push('config.base_url is required (use empty string for root)');
  }

  // Google Analytics 4 ID format
  if (
    config.google_analytics_id &&
    !/^G-[A-Z0-9]+$/.test(config.google_analytics_id)
  ) {
    warnings.push(
      `config.google_analytics_id "${config.google_analytics_id}" does not look like a valid GA4 measurement ID (expected format: G-XXXXXXXXXX)`,
    );
  }

  // CSP nonce type
  if (config.csp_nonce !== undefined && typeof config.csp_nonce !== 'boolean') {
    errors.push('config.csp_nonce must be a boolean');
  }

  // Security: editing enabled without any authentication
  if (
    config.allow_editing === true &&
    config.authentication !== true &&
    config.authentication_for_edit !== true &&
    config.googleoauth !== true
  ) {
    warnings.push(
      'config.allow_editing is true but no authentication is configured — anyone can edit content',
    );
  }

  // Credentials when authentication is enabled
  if (config.authentication === true && config.googleoauth !== true) {
    if (!Array.isArray(config.credentials) || config.credentials.length === 0) {
      const cred = generateCredentials();
      config.credentials = [cred];
      console.log(
        `No credentials configured — generated credentials for this session:\n  username: ${cred.username}\n  password: ${cred.password}`,
      );
    } else {
      config.credentials.forEach((cred, i) => {
        if (!cred.username || !cred.password) {
          errors.push(
            `config.credentials[${i}] must have username and password`,
          );
        } else {
          const entropy = passwordEntropy(cred.password);
          if (entropy < MIN_PASSWORD_ENTROPY_BITS) {
            errors.push(
              `config.credentials[${i}] password is too weak (${Math.floor(entropy)} bits entropy, minimum ${MIN_PASSWORD_ENTROPY_BITS}); use a longer password with mixed character types`,
            );
          }
        }
      });
    }
  }

  // OAuth2 when enabled
  if (config.googleoauth === true) {
    if (!config.oauth2 || typeof config.oauth2 !== 'object') {
      errors.push(
        'config.oauth2 object is required when googleoauth is enabled',
      );
    } else {
      require(config.oauth2.client_id, 'config.oauth2.client_id is required');
      require(config.oauth2
        .client_secret, 'config.oauth2.client_secret is required');
      require(config.oauth2.callback, 'config.oauth2.callback is required');
    }

    // Google group restriction
    if (config.google_group_restriction?.enabled) {
      require(config.google_group_restriction
        .group_name, 'config.google_group_restriction.group_name is required when enabled');
      require(config.google_group_restriction
        .api_key, 'config.google_group_restriction.api_key is required when enabled');
    }
  }

  if (warnings.length > 0) {
    console.warn(`Config warnings:\n  - ${warnings.join('\n  - ')}`);
  }

  if (errors.length > 0) {
    throw new Error(`Config validation failed:\n  - ${errors.join('\n  - ')}`);
  }
}

export default validateConfig;
